blank_issues_enabled: false
contact_links:
  - name: 💬 Django India Telegram
    url: https://t.me/djangoindiaa
    about: Please use the Telegram group to connect with fellow Pythonistas in and around Delhi/NCR.
  - name: Q/A Forum
    url: https://github.com/orgs/pydelhi/discussions
    about: Use the forum to ask questions about the meetup, help us with Sponsorship, or anything else.